DROP DATABASE IF EXISTS bookmarkDB;

CREATE DATABASE bookmarkDB;

USE bookmarkDB;

CREATE TABLE IF NOT EXISTS `Users` (
	  `UserID` INT NOT NULL AUTO_INCREMENT,
	  `Username` VARCHAR(45) NOT NULL,
	  `Password` VARCHAR(45) NOT NULL,
	  PRIMARY KEY (`UserID`));

CREATE TABLE IF NOT EXISTS `Bookmarks` (
  `BookmarkID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `Url` VARCHAR(450) NOT NULL,
   PRIMARY KEY (`BookmarkID`, `UserID`),
   CONSTRAINT FK_UserBookmark FOREIGN KEY (UserID)
   REFERENCES `Users`(UserID)
   ON DELETE NO ACTION
   ON UPDATE NO ACTION   
);
